version: '2'
services:
  app:
     build:
        context: .
     links:
        - redis
  redis:
      image: redis:5.0.4
  nginx:
      image: nginx:1.16.0
      links:
         - app
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      ports:
        - 80:80
